name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the Snake
        uses: Platane/snk@master
        with:
          github_user_name: JonyOner
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
